# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: list all command
    cmds:
      - task --list-all

  run-server:
    desc: run dev server
    cmds:
      - python manage.py runserver
    aliases:
      - rs

  run-prod-server:
    desc: run prod server
    cmds:
      - gunicorn --bind 0.0.0.0:8000 code_builder.wsgi
    aliases:
      - rps

  update-database:
    desc: make migration and migrate
    cmds:
      - python manage.py migrate django_celery_results
      - python manage.py makemigrations
      - python manage.py migrate
    aliases:
      - upd

  run-controller:
    desc: run compile controller
    cmds:
      - python manage.py run_controller

  start-redis-server:
    desc: start redis server
    cmds:
      - docker run -d -p 6379:6379 redis || true
    aliases:
      - redis

  start-celery-worker:
    desc: start celery worker
    cmds:
      - celery -A code_builder worker -l INFO

  build-docker-image:
    desc: build docker image
    cmds:
      - docker build -t code-builder:latest -f Dockerfile .
    aliases:
      - b