# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: list all command
    cmds:
      - task --list-all

  run-server:
    desc: run dev server
    cmds:
      - python manage.py runserver
    aliases:
      - rs

  update-database:
    desc: make migration and migrate
    cmds:
      - python manage.py migrate django_celery_results
      - python manage.py makemigrations
      - python manage.py migrate
    aliases:
      - upd

  start-redis-server:
    desc: start redis server
    cmds:
      - docker run -d -p 6380:6379 redis || true
    aliases:
      - redis

  start-celery-worker:
    desc: start celery worker
    cmds:
      - celery -A code_builder worker -l INFO