# Generated by Django 4.2.1 on 2023-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compileworkflow',
            name='code_source',
            field=models.TextField(default='INITIALIZED'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compileworkflow',
            name='status',
            field=models.CharField(choices=[('INITIALIZED', 'Initialized'), ('COMPILING', 'Compiling'), ('COMPILING_ERROR', 'Compiling Error'), ('EXECUTION_ERROR', 'Execution Error'), ('EXECUTED', 'Executed')], default='INITIALIZED', max_length=300),
        ),
        migrations.AlterField(
            model_name='compileworkflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
