# Generated by Django 4.2.1 on 2023-05-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_compileworkflow_code_source_compileworkflow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compileworkflow',
            name='wf_exec_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compileworkflow',
            name='wf_exec_stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compileworkflow',
            name='wf_exec_stdout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compileworkflow',
            name='wf_log_compilation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
