# Generated by Django 4.2.1 on 2023-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_compileworkflow_wf_exec_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compileworkflow',
            name='wf_compiled_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compileworkflow',
            name='status',
            field=models.CharField(choices=[('INITIALIZED', 'Initialized'), ('COMPILING', 'Compiling'), ('NO_CODE_SOURCE_ERROR', 'No code source error'), ('COMPILED_SUCCESS', 'Compiled success'), ('COMPILING_ERROR', 'Compiling error'), ('EXECUTING', 'Executing'), ('EXECUTION_ERROR', 'Execution error'), ('EXECUTED', 'Executed')], default='INITIALIZED', max_length=300),
        ),
    ]
