# Generated by Django 4.2.1 on 2023-06-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_compileworkflow_wf_compiled_binary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compileworkflow',
            old_name='code_source',
            new_name='source_code',
        ),
        migrations.RenameField(
            model_name='compileworkflow',
            old_name='wf_exec_stderr',
            new_name='wf_exec_logs',
        ),
        migrations.RemoveField(
            model_name='compileworkflow',
            name='wf_exec_stdout',
        ),
    ]
